# netlify.toml
# Este archivo configura cómo Netlify construye y despliega tu proyecto.

[build]
  # 'publish' indica la carpeta que contiene los archivos de tu sitio web estático (HTML, CSS, JS).
  publish = "/"

# Configuración para el entorno de desarrollo local con 'netlify dev'.
[dev]
  framework = "#static"
  targetPort = 8888

# Configuración para las Netlify Functions.
[functions]
  # 'directory' es CRUCIAL y le dice a Netlify dónde encontrar tus funciones.
  directory = "netlify/functions"
  node_bundler = "esbuild"
  # Hemos ELIMINADO la línea 'node_version' y la línea 'external_node_modules'
  # para evitar el conflicto de sintaxis que tu CLI está reportando persistentemente.
  # Netlify usará una versión de Node.js por defecto para tus funciones, que debería ser compatible.

  # Configuración específica para tu función 'generate-session'.
  [functions.generate-session]
    timeout = 60 # Tiempo de espera para esta función en segundos

  # Configuración específica para tu función 'generate-word'.
  [functions.generate-word]
    timeout = 60 # Asignamos un timeout por si es una función larga

# Reglas de redirección.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200